### ISSUE TITLE
Question about IntelliMind3? 

### ISSUE THREAD

**Issue by Jariell** [keawe-software/intelliMind#5]
Hello, I was doing a search this evening and came about your mindmapping application IntelliMind3 which I am very enthused in. Can it be downloaded? Note, I found on Github, as well... may you be able to provide some instructions on compiling, if it is necessary? Sincerely, thank you. I like the fact of the radial nature of the mind map and that you can link the nodes to other mind maps. Seems very nice, something like this which I have been enthused in. I like the fact that it has compatibility with freemind format, also.  I want to thank you for developing this application. Ok, I won't say much more. 

All the best for the new year... Jariell

**Comment by StephanRichter** [comment]
Hey there!

Thank you for your interest. You have two possibilities:
- either you download the [precompiled jar](https://github.com/keawe-software/intelliMind/blob/master/jar/intelliMind.jar) file and run it with `java -jar intelliMind.jar`
- or you compile it (for example using eclipse under linux) with the following steps:<br>
  `git clone https://github.com/keawe-software/intelliMind`<br>
  `cd intelliMind`<br>
  `git submodule init`<br>
  `git submodule update`<br>
  `scripts/versionupdate`
  then import it in eclipse and you should be able to launch it from eclipse

**Comment by Jariell** [comment]
Thank you, I just downloaded it... I will learn how to compile it, also... I installed Eclipse on Windows and was able to import the project through Git repository. I just came back and saw your post. 
I wasn't able to compile it before I saw your instructions, but I will try on Linux. Your instrctions will make it straight forward.

Sincerely, have a very wonderful beginning of the New Year.
